project:
  type: website
  output-dir: docs

website:
  sidebar: 
     style: docked
     search: true
     contents: 
     - section: "Inicio"
       contents:
       - index.qmd
     - section: "Base de Datos"
       contents:
       -  Base_Datos.qmd

  #title: "Replica: Testing Broken Windows"
  #navbar:
   # left:
    #  - href: Base_Datos.qmd
     #   text: Base de Datos 

format:
  html:
    theme: flatly
    mainfont: Montserrat
    css: styles.css
    toc: true



