project:
  type: website
  output-dir: docs

website:
  title: "Replica: Testing Broken Windows"
  navbar:
    left:
      - href: Base_Datos.qmd
        text: Base de Datos 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



